#!/bin/sh

proc=`ps -ef | grep j_make_stamp | grep -v vi |grep -v grep | grep -v sh`
if [ X"$proc" != X"" ]; then
	echo "Already Invoked"
	exit
fi

cd ..
java -jar j_make_stamp.war config/stamp > logs/sysout.log &
